#!/bin/sh
#
# init script for CANE
#

### BEGIN INIT INFO
# Provides:          CANE
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for CANE
# Description:       Handles automatic CANE initation.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=cane
FILE=/home/pi/CANE/startCane.sh
LOGFILE=/var/log/$NAME.log

. /lib/lsb/init-functions

test -f $DAEMON || exit 0

case "$1" in
    start)
        sleep 30s ###Prevents race condition with CANE-SOUND.  Without this, CANE-SOUND could potentially not be up.
        /bin/bash /home/pi/CANE/startCane.sh
        ;;
    stop)
        killall python*
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac

exit 0
